services:
  - type: web
    name: thermotrace-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8000
      - key: ENABLE_FIRMS_POLLING
        value: "false"
      - key: FIRMS_POLL_INTERVAL_MINUTES
        value: "60"
      - key: FIRMS_MAP_KEY
        value: "5ee48ea9900661577c1dc26dfcc70550"
      - key: DATABASE_URL
        value: "postgresql://postgres.mlkgaoxnvptewcxblmes:Sharan1%40bmsce@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres"
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
